import { Link } from 'react-router-dom'

const steps = [['01', 'Share your target', 'Tell us your ZIP, preferred shift, and eligibility.'], ['02', 'We watch the window', 'Our team monitors openings and matches the right fit.'], ['03', 'You move quickly', 'Get an alert, claim the slot, and keep your momentum.']]
const features = [['LIVE', 'Slot signal monitoring', 'Stay close to the openings that matter.'], ['24/7', 'Always-on attention', 'Human review stays in the loop around the clock.'], ['98%', 'Profile readiness', 'Clear mapping makes every application stronger.']]

export default function HomePage() {
  return <main>
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow">THE PLACEMENT OPERATIONS DESK</p><h1>Automated Amazon Shift &amp; Slot Matcher for Job Seekers</h1><p className="hero-lede">The signal is fast. The judgment is human. TalentPath helps job seekers move from eligibility to the right Amazon opportunity without losing the window.</p><div className="hero-actions"><Link className="btn" to="/register">Get Started <span>→</span></Link><Link className="text-link" to="/login">Client Login <span>↗</span></Link><Link className="text-link" to="/contact">Contact Us</Link></div></div><div className="signal-board"><div className="signal-top"><span>PLACEMENT SIGNAL</span><span className="signal-live">● LIVE</span></div><div className="signal-title">Night shift / Fulfillment</div><div className="signal-meta"><span>ZIP 75001</span><span>Eligibility verified</span></div><div className="signal-line"><i /><b>92%</b><span>match confidence</span></div><div className="signal-footer">Alert ready <span>Just now</span></div></div></section>
    <section className="section intro-section"><p className="eyebrow">A BETTER HANDOFF</p><h2>Good placement is a series of small, well-timed decisions.</h2><p className="section-lede">We combine alert automation with a real placement desk, so candidates get speed without being left to decode a portal alone.</p><div className="step-grid">{steps.map(([n, title, text]) => <div className="step" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="feature-band"><div><p className="eyebrow">BUILT FOR THE WINDOW</p><h2>Clarity when the clock is moving.</h2></div><div className="feature-grid">{features.map(([metric, title, text]) => <div className="feature" key={title}><strong>{metric}</strong><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="section testimonial"><p className="eyebrow">FROM THE DESK</p><blockquote>“I stopped refreshing three different places. TalentPath told me what mattered and helped me act on it.”</blockquote><p className="quote-by">Ayesha R. · Fulfillment candidate</p></section>
  </main>
}